export const SET_USER = 'SET_USER';
export const REQUEST_FRIENDS = 'REQUEST_FRIENDS';
export const RECEIVE_FRIENDS = 'RECEIVE_FRIENDS';
export const START_QUILT = 'START_QUILT';
export const REQUEST_QUILTS = 'REQUEST_QUILTS';
export const RECEIVE_QUILTS = 'RECEIVE_QUILTS';
