export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const REQUEST_FRIENDS = 'REQUEST_FRIENDS';
export const RECEIVE_FRIENDS = 'RECEIVE_FRIENDS';
export const SELECT_WATCH_QUILT = 'SELECT_WATCH_QUILT';
export const REQUEST_QUILTS = 'REQUEST_QUILTS';
export const RECEIVE_QUILTS = 'RECEIVE_QUILTS';
export const REQUEST_POST_QUILT = 'REQUEST_POST_QUILT';
export const RECEIVE_POST_QUILT = 'RECEIVE_POST_QUILT';
export const REQUEST_ADD_QUILT = 'REQUEST_ADD_QUILT';
export const RESPONSE_ADD_QUILT = 'RESPONSE_ADD_QUILT';
export const INVITE_FRIENDS = 'INVITE_FRIENDS';

export const CREATE_QUILT = 'CREATE_QUILT';
export const ADD_TO_QUILT = 'ADD_TO_QUILT';
export const WATCH_QUILT = 'WATCH_QUILT';
export const REVIEW_QUILT = 'REVIEW_QUILT';

export const LOGIN_OR_SIGNUP = 'LOGIN_OR_SIGNUP';

export const SET_USERNAME = 'SET_USERNAME';
export const ADD_PHONE_NUMBER = 'ADD_PHONE_NUMBER';
export const RECEIVE_USER_ERROR = 'RECEIVE_USER_ERROR';
export const RECEIVE_USERNAME_EXIST_ERROR = 'RECEIVE_USERNAME_EXIST_ERROR';
